---
op_kubeconfig: ""
hcp_namespace: clusters
guest_kubeconfig_dir: "{{ install_root }}/guests"
guest_release_image: "quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64"
nodepool_timeout: 3600
