#!/bin/bash
# Regenerate the Ansible inventory from recorded stack state.
#
# The bastion is the only host Ansible connects to. It runs openshift-install
# and every oc call, because it is inside the VPC and can therefore resolve the
# private hosted zone that api-int lives in -- a workstation cannot.
set -euo pipefail
# shellcheck source=../../common.sh
source "$(dirname "${BASH_SOURCE[0]}")/../../common.sh"

load_config

PUBLIC_IP="$(read_state public_address)"
[ -n "${PUBLIC_IP}" ] || die "no bastion recorded; run 'make infra' first"

INVENTORY="${REPO_ROOT}/deploy/openshift-clusters/inventory.ini"
cat > "${INVENTORY}" <<INV
# Generated by deploy/aws-infra/scripts/inventory.sh -- edits are overwritten.
[bastion]
${PUBLIC_IP} ansible_user=$(read_state ssh_user) ansible_ssh_private_key_file=${SSH_PRIVATE_KEY}

[bastion:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
INV

green "wrote ${INVENTORY} (bastion ${PUBLIC_IP})"
