#!/bin/bash
# Regenerate the Ansible inventory from recorded stack state.
#
# The bastion is the only host Ansible connects to. It runs openshift-install
# and every oc call, because it is inside the VPC and can therefore resolve the
# private hosted zone that api-int lives in -- a workstation cannot.
set -euo pipefail
# shellcheck source=../../common.sh
source "$(dirname "${BASH_SOURCE[0]}")/../../common.sh"

load_config

PUBLIC_IP="$(read_state public_address)"
[ -n "${PUBLIC_IP}" ] || die "no bastion recorded; run 'make infra' first"

ACM_PUBLIC_IP="$(read_acm_state public_address)"

INVENTORY="${REPO_ROOT}/deploy/openshift-clusters/inventory.ini"
cat > "${INVENTORY}" <<INV
# Generated by deploy/aws-infra/scripts/inventory.sh -- edits are overwritten.
#
# Two sites, each with its own bastion. Playbooks target one or the other: the
# TNF stages run against [bastion], the ACM stages against [acm_bastion]. They
# reach each other over the VPC peering connection, not through here.
[bastion]
${PUBLIC_IP} ansible_user=$(read_state ssh_user) ansible_ssh_private_key_file=${SSH_PRIVATE_KEY}
INV

if [ -n "${ACM_PUBLIC_IP}" ]; then
  cat >> "${INVENTORY}" <<INV

[acm_bastion]
${ACM_PUBLIC_IP} ansible_user=$(read_acm_state ssh_user) ansible_ssh_private_key_file=${SSH_PRIVATE_KEY}
INV
fi

cat >> "${INVENTORY}" <<INV

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
INV

green "wrote ${INVENTORY} (TNF bastion ${PUBLIC_IP}${ACM_PUBLIC_IP:+, ACM bastion ${ACM_PUBLIC_IP}})"
